### ISSUE TITLE
syntax error

### ISSUE THREAD

**Issue by privacy313** [ronniedroid/Wall-d#3]
can't get this to work.
wall-d prints

```
defaultwallpaper.sh exists
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
(standard_in) 2: syntax error
```

then sxiv launches with a preview of my wallpapers dir, selecting a wallpaper simply enlarges it.. not setting the wallpaper.

**Comment by ronniedroid** [comment]
Send me the command you are using please.

To set a wallpaper, you select it with `m` then quite sxiv with `q` then you'll get some options with dmenu (or rofi if you run it with the `-R` flag).

**Comment by privacy313** [comment]
i'm simply running `wall-d` either from the terminal or from dmenu.
it's placed in my ~/.local/bin.

using m to select the wallpaper works and gives me the dmenu prompt - however it seems to want xwallpaper installed to set the background (even though i have feh installed).
if i install xwallpaper it will set the background but not change pywal colours.

**Comment by ronniedroid** [comment]
You should read the usage,  to use feh instead of xwallpaper you need to use the `-f` flag, to use pywal you should use the `-p` flag. Please read the readme

**Comment by privacy313** [comment]
d'oh. working fine now - thanks.
